name: Feature Branch CI

on:
  push:
    branches:
      - 'feature/**'
  workflow_dispatch:

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Make mvnw executable
      run: chmod +x ./mvnw

    - name: Install dependencies
      run: ./mvnw dependency:resolve -B

    - name: Run tests with coverage
      run: ./mvnw test -B

    - name: Build application
      run: ./mvnw package -DskipTests -B
